site_name: JackTrip
repo_url: https://github.com/jacktrip/jacktrip
nav:
  - Home: index.md
  - User Guide:
    - Installation: Install.md
  - Developer Guide:
    - Linux: Build/Linux.md
    - Mac OS: Build/Mac.md
    - Windows: Build/Windows.md
    - Meson Build: Build/Meson_build.md
    - Write Documentation: Documentation/MkDocs.md
  - About:
    - Resources: About/Resources.md
    - Changelog: About/CHANGELOG.md
    - Todo: About/Todo.md
    - License: About/License.md
theme:
  name: material
  features:
    - navigation.tabs
markdown_extensions:
  - pymdownx.snippets
